# Generated by Django 3.1.3 on 2020-12-17 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0003_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='remainNum',
            field=models.IntegerField(default=0),
        ),
    ]
