# Generated by Django 3.1.3 on 2020-12-17 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0004_product_remainnum'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='remainNum',
            new_name='rest',
        ),
    ]
