# Generated by Django 3.1.3 on 2020-12-17 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0005_auto_20201217_1238'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='rest',
            new_name='restp',
        ),
    ]
